### ISSUE TITLE
@propaty でのエラー　(help)

### ISSUE THREAD

**Issue by yuto-kakitani** [PRMLmasters/PRML#17]
BinomialDistributionでの

@propaty
def expected_value(self):
...
において、このメソッドを実行すると

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object is not callable

と出ました。

理由がよくわからず、一旦@propatyをコメントアウトすると正常に実行されました。
同じことがvarianceにおいても確認できました。
これは一体どういうことでしょうか？

**Comment by yasudadesu** [comment]
propertyはメソッドじゃないからですかね？
`hoge.expected_value()`って呼んでません？

追記:
`hoge.expected_value`自体が値なので、それは`not callable`ですよということです

**Comment by yuto-kakitani** [comment]
そうしていました...
なるほど、自分のリサーチ不足でした
ありがとうございます！
